# Base configs
baseurl: "https://haithao.github.io/tuongart"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# defaul
defaults:
  - scope:
      path: "/images"
    values:
      image: true

# UI configs
title: "Tranh cua hoa sy Dang Tin Tuong"
subtitle: "See the world through my eyes!"
author: "Dang Tin Tuong"
header:
 title: "Paiting"
 subtitle: "by Dang Tin Tuong"
footer:
 name: "Dang Tin Tuong"
 bio: " Với tôi được vẽ là sung sướng nhất "
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
